#!/bin/bash
#
# swarm  agent
#
# chkconfig: 2345 55 25
# description: Swarm Agent
#
# processname: swarm-agent

# pidfile: /var/run/swarmagent.pid

### BEGIN INIT INFO
# Provides: swarmagent
# Required-Start: $local_fs $network $syslog
# Required-Stop: $local_fs $syslog
# Should-Stop: $network $syslog
# Default-Start: 
# Default-Stop: 0 1 6
# Short-Description: Start up the swarm agent
# Description: swarm agent.
### END INIT INFO

# source function library
. /etc/rc.d/init.d/functions

# pull in sysconfig settings
[ -f /etc/sysconfig/swarm ] && . /etc/sysconfig/swarm

RETVAL=0
prog="swarmclient"
lockfile=/var/lock/subsys/$prog

# Some functions to make the below more readable
PIDFILE=/var/run/$prog.pid

LOG=/var/log/swarm/swarm.log
USER=jenkins



start()
{
# Execute ourself in a background mode
echo "$$" > $PIDFILE
runuser $USER -c "${0} start_background &"
echo -n "Starting Application: "
success "Starting Application: "
touch $lockfile
echo
}

start_background()
{
# Remember PID
exec $SWARM $SWARM_OPTIONS 2>&1 | tee -a "$LOG" > /dev/null
}

stop()
{
if [ -f ${PIDFILE} ]; then
  kill `cat $PIDFILE`
  rm -f $PIDFILE
  rm -f $logfile
  echo -n "Stopping Application: "
  success "Stopping Application: "
  echo
fi
}

case "$1" in
start)
start
;;
start_background)
start_background
;;
stop)
stop
;;
restart)
stop
start
;;
*)
echo "Usage $0 {start|stop|restart}"
exit 1
esac
exit 0
